### ISSUE TITLE
使用远程桌面或Steam 串流时鼠标坐标不对应

### ISSUE THREAD

**Issue by 123456ds** [Blinue/Magpie#674] opened 2023-07-10 02:31 UTC
### Magpie version 程序版本

0.10.3

### Windows version 系统版本

win10 22h2

### Related screenshot (optional) 相关截图（可选）

![Screenshot_20230710_101603.jpg](https://p.inari.site/guest/23-07/10/64ab6d36ef285.jpg)
![Screenshot_20230710_101639.jpg](https://p.inari.site/guest/23-07/10/64ab6d376567f.jpg)

### Reproduction steps 复现步骤

使用远程桌面或Steam 串流时鼠标坐标不对应

### Log files 日志文件

2023-07-10 09:19:47.608|info|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_CreateHostWnd(void)|缩放窗口尺寸：1920x1080
2023-07-10 09:19:47.611|info|DeviceResources.cpp:bool __cdecl Magpie::Core::DeviceResources::Initialize(void)|可变刷新率支持：是
2023-07-10 09:19:47.628|info|DeviceResources.cpp:bool __cdecl Magpie::Core::DeviceResources::_TryCreateD3DDevice(struct IDXGIAdapter1 *) noexcept|已创建 D3D Device
	功能级别：11.1
2023-07-10 09:19:47.628|info|DeviceResources.cpp:void __cdecl Magpie::Core::LogAdapter(const struct DXGI_ADAPTER_DESC1 &)|当前图形适配器：
	VendorId：0x1002
	DeviceId：0x1638
	描述：AMD Radeon(TM) Graphics
2023-07-10 09:19:47.630|info|DeviceResources.cpp:bool __cdecl Magpie::Core::DeviceResources::_CreateSwapChain(void)|Hardware Composition 支持：是
2023-07-10 09:19:47.630|info|DeviceResources.cpp:bool __cdecl Magpie::Core::DeviceResources::_CreateSwapChain(void)|Multiplane Overlay 支持：是
2023-07-10 09:19:47.630|info|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_InitFrameSource(void)|当前捕获模式：Graphics Capture
2023-07-10 09:19:47.649|info|GraphicsCaptureFrameSource.cpp:bool __cdecl Magpie::Core::GraphicsCaptureFrameSource::Initialize(void)|GraphicsCaptureFrameSource 初始化完成
2023-07-10 09:19:47.649|info|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_InitFrameSource(void)|源窗口尺寸：1280x720
2023-07-10 09:19:47.922|info|EffectCacheManager.cpp:void __cdecl Magpie::Core::EffectCacheManager::Save(class std::basic_string_view<wchar_t,struct std::char_traits<wchar_t> >,class std::basic_string_view<wchar_t,struct std::char_traits<wchar_t> >,const struct Magpie::Core::EffectDesc &)|已保存缓存 cache\Lanczos_1cfc88f88f10091e3
2023-07-10 09:19:47.922|info|Renderer.cpp:bool __cdecl Magpie::Core::CompileEffect(bool,const struct Magpie::Core::EffectOption &,struct Magpie::Core::EffectDesc &)|编译 Lanczos.hlsl 用时 273.552 毫秒
2023-07-10 09:19:47.979|info|CursorManager.cpp:bool __cdecl Magpie::Core::CursorManager::Initialize(void)|CursorManager 初始化完成
2023-07-10 09:19:48.297|info|CursorManager.cpp:bool __cdecl Magpie::Core::CursorManager::GetCursorTexture(struct ID3D11Texture2D **,enum Magpie::Core::CursorManager::CursorType &)|已解析光标：0x10003
	类型：Color
2023-07-10 09:45:21.384|info|Renderer.cpp:int __cdecl Magpie::Core::Renderer::_CheckSrcState(void)|前台窗口已改变
2023-07-10 09:45:21.384|info|Renderer.cpp:void __cdecl Magpie::Core::Renderer::Render(bool)|源窗口状态改变，退出全屏
2023-07-10 09:45:28.067|info|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_CreateHostWnd(void)|缩放窗口尺寸：1920x1080
2023-07-10 09:45:28.069|info|DeviceResources.cpp:bool __cdecl Magpie::Core::DeviceResources::Initialize(void)|可变刷新率支持：是
2023-07-10 09:45:28.089|info|DeviceResources.cpp:bool __cdecl Magpie::Core::DeviceResources::_TryCreateD3DDevice(struct IDXGIAdapter1 *) noexcept|已创建 D3D Device
	功能级别：11.1
2023-07-10 09:45:28.089|info|DeviceResources.cpp:void __cdecl Magpie::Core::LogAdapter(const struct DXGI_ADAPTER_DESC1 &)|当前图形适配器：
	VendorId：0x1002
	DeviceId：0x1638
	描述：AMD Radeon(TM) Graphics
2023-07-10 09:45:28.091|info|DeviceResources.cpp:bool __cdecl Magpie::Core::DeviceResources::_CreateSwapChain(void)|Hardware Composition 支持：是
2023-07-10 09:45:28.091|info|DeviceResources.cpp:bool __cdecl Magpie::Core::DeviceResources::_CreateSwapChain(void)|Multiplane Overlay 支持：是
2023-07-10 09:45:28.091|info|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_InitFrameSource(void)|当前捕获模式：Graphics Capture
2023-07-10 09:45:28.106|info|GraphicsCaptureFrameSource.cpp:bool __cdecl Magpie::Core::GraphicsCaptureFrameSource::Initialize(void)|GraphicsCaptureFrameSource 初始化完成
2023-07-10 09:45:28.106|info|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_InitFrameSource(void)|源窗口尺寸：1280x720
2023-07-10 09:45:28.107|info|Win32Utils.cpp:bool __cdecl Win32Utils::ReadFile(const wchar_t *,class std::vector<unsigned char,class std::allocator<unsigned char> > &)|读取文件：cache\Lanczos_1cfc88f88f10091e3
2023-07-10 09:45:28.107|info|EffectCacheManager.cpp:bool __cdecl Magpie::Core::EffectCacheManager::Load(class std::basic_string_view<wchar_t,struct std::char_traits<wchar_t> >,class std::basic_string_view<wchar_t,struct std::char_traits<wchar_t> >,struct Magpie::Core::EffectDesc &)|已读取缓存 cache\Lanczos_1cfc88f88f10091e3
2023-07-10 09:45:28.107|info|Renderer.cpp:bool __cdecl Magpie::Core::CompileEffect(bool,const struct Magpie::Core::EffectOption &,struct Magpie::Core::EffectDesc &)|编译 Lanczos.hlsl 用时 0.36100003 毫秒
2023-07-10 09:45:28.108|info|CursorManager.cpp:bool __cdecl Magpie::Core::CursorManager::Initialize(void)|CursorManager 初始化完成
2023-07-10 09:56:44.385|info|Renderer.cpp:int __cdecl Magpie::Core::Renderer::_CheckSrcState(void)|前台窗口已改变
2023-07-10 09:56:44.385|info|Renderer.cpp:void __cdecl Magpie::Core::Renderer::Render(bool)|源窗口状态改变，退出全屏
2023-07-10 10:01:14.956|error|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_CreateHostWnd(void)|已存在缩放窗口
2023-07-10 10:01:16.336|error|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_CreateHostWnd(void)|已存在缩放窗口
2023-07-10 10:01:17.478|error|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_CreateHostWnd(void)|已存在缩放窗口
2023-07-10 10:01:18.198|error|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_CreateHostWnd(void)|已存在缩放窗口
2023-07-10 10:01:18.457|error|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_CreateHostWnd(void)|已存在缩放窗口
2023-07-10 10:01:24.566|error|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_CreateHostWnd(void)|已存在缩放窗口
2023-07-10 10:01:25.702|error|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_CreateHostWnd(void)|已存在缩放窗口
2023-07-10 10:01:26.998|error|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_CreateHostWnd(void)|已存在缩放窗口
2023-07-10 10:01:50.339|error|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_CreateHostWnd(void)|已存在缩放窗口
2023-07-10 10:01:51.746|error|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_CreateHostWnd(void)|已存在缩放窗口
2023-07-10 10:01:52.558|error|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_CreateHostWnd(void)|已存在缩放窗口
2023-07-10 10:01:56.961|error|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_CreateHostWnd(void)|已存在缩放窗口
2023-07-10 10:01:58.218|error|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_CreateHostWnd(void)|已存在缩放窗口
2023-07-10 10:01:58.790|error|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_CreateHostWnd(void)|已存在缩放窗口
2023-07-10 10:01:59.508|error|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_CreateHostWnd(void)|已存在缩放窗口
2023-07-10 10:01:59.800|error|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_CreateHostWnd(void)|已存在缩放窗口
2023-07-10 10:02:00.107|error|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_CreateHostWnd(void)|已存在缩放窗口
2023-07-10 10:02:00.583|error|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_CreateHostWnd(void)|已存在缩放窗口
2023-07-10 10:02:01.106|error|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_CreateHostWnd(void)|已存在缩放窗口
2023-07-10 10:02:07.164|error|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_CreateHostWnd(void)|已存在缩放窗口
2023-07-10 10:02:08.721|error|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_CreateHostWnd(void)|已存在缩放窗口
2023-07-10 10:15:06.464|info|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_CreateHostWnd(void)|缩放窗口尺寸：1920x1080
2023-07-10 10:15:06.466|info|DeviceResources.cpp:bool __cdecl Magpie::Core::DeviceResources::Initialize(void)|可变刷新率支持：是
2023-07-10 10:15:06.483|info|DeviceResources.cpp:bool __cdecl Magpie::Core::DeviceResources::_TryCreateD3DDevice(struct IDXGIAdapter1 *) noexcept|已创建 D3D Device
	功能级别：11.1
2023-07-10 10:15:06.483|info|DeviceResources.cpp:void __cdecl Magpie::Core::LogAdapter(const struct DXGI_ADAPTER_DESC1 &)|当前图形适配器：
	VendorId：0x1002
	DeviceId：0x1638
	描述：AMD Radeon(TM) Graphics
2023-07-10 10:15:06.484|info|DeviceResources.cpp:bool __cdecl Magpie::Core::DeviceResources::_CreateSwapChain(void)|Hardware Composition 支持：是
2023-07-10 10:15:06.484|info|DeviceResources.cpp:bool __cdecl Magpie::Core::DeviceResources::_CreateSwapChain(void)|Multiplane Overlay 支持：是
2023-07-10 10:15:06.484|info|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_InitFrameSource(void)|当前捕获模式：Graphics Capture
2023-07-10 10:15:06.500|info|GraphicsCaptureFrameSource.cpp:bool __cdecl Magpie::Core::GraphicsCaptureFrameSource::Initialize(void)|GraphicsCaptureFrameSource 初始化完成
2023-07-10 10:15:06.500|info|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_InitFrameSource(void)|源窗口尺寸：1279x719
2023-07-10 10:15:06.500|info|Win32Utils.cpp:bool __cdecl Win32Utils::ReadFile(const wchar_t *,class std::vector<unsigned char,class std::allocator<unsigned char> > &)|读取文件：cache\Lanczos_1cfc88f88f10091e3
2023-07-10 10:15:06.500|info|EffectCacheManager.cpp:bool __cdecl Magpie::Core::EffectCacheManager::Load(class std::basic_string_view<wchar_t,struct std::char_traits<wchar_t> >,class std::basic_string_view<wchar_t,struct std::char_traits<wchar_t> >,struct Magpie::Core::EffectDesc &)|已读取缓存 cache\Lanczos_1cfc88f88f10091e3
2023-07-10 10:15:06.500|info|Renderer.cpp:bool __cdecl Magpie::Core::CompileEffect(bool,const struct Magpie::Core::EffectOption &,struct Magpie::Core::EffectDesc &)|编译 Lanczos.hlsl 用时 0.245 毫秒
2023-07-10 10:15:06.501|info|ImGuiImpl.cpp:unsigned long __cdecl Magpie::Core::ThreadProc(void *)|已注册鼠标钩子
2023-07-10 10:15:06.501|info|Win32Utils.cpp:bool __cdecl Win32Utils::ReadFile(const wchar_t *,class std::vector<unsigned char,class std::allocator<unsigned char> > &)|读取文件：C:\Windows\Fonts\segoeui.ttf
2023-07-10 10:15:06.506|info|CursorManager.cpp:bool __cdecl Magpie::Core::CursorManager::Initialize(void)|CursorManager 初始化完成
2023-07-10 10:15:07.081|info|CursorManager.cpp:bool __cdecl Magpie::Core::CursorManager::GetCursorTexture(struct ID3D11Texture2D **,enum Magpie::Core::CursorManager::CursorType &)|已解析光标：0x10003
	类型：Color
2023-07-10 10:15:19.980|info|CursorManager.cpp:bool __cdecl Magpie::Core::CursorManager::GetCursorTexture(struct ID3D11Texture2D **,enum Magpie::Core::CursorManager::CursorType &)|已解析光标：0x10019
	类型：Color
2023-07-10 10:15:56.400|info|CursorManager.cpp:bool __cdecl Magpie::Core::CursorManager::GetCursorTexture(struct ID3D11Texture2D **,enum Magpie::Core::CursorManager::CursorType &)|已解析光标：0xa07b3
	类型：Monochrome
2023-07-10 10:16:14.263|info|ImGuiImpl.cpp:unsigned long __cdecl Magpie::Core::ThreadProc(void *)|已销毁鼠标钩子
2023-07-10 10:16:18.240|info|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_CreateHostWnd(void)|缩放窗口尺寸：1920x1080
2023-07-10 10:16:18.243|info|DeviceResources.cpp:bool __cdecl Magpie::Core::DeviceResources::Initialize(void)|可变刷新率支持：是
2023-07-10 10:16:18.260|info|DeviceResources.cpp:bool __cdecl Magpie::Core::DeviceResources::_TryCreateD3DDevice(struct IDXGIAdapter1 *) noexcept|已创建 D3D Device
	功能级别：11.1
2023-07-10 10:16:18.260|info|DeviceResources.cpp:void __cdecl Magpie::Core::LogAdapter(const struct DXGI_ADAPTER_DESC1 &)|当前图形适配器：
	VendorId：0x1002
	DeviceId：0x1638
	描述：AMD Radeon(TM) Graphics
2023-07-10 10:16:18.262|info|DeviceResources.cpp:bool __cdecl Magpie::Core::DeviceResources::_CreateSwapChain(void)|Hardware Composition 支持：是
2023-07-10 10:16:18.262|info|DeviceResources.cpp:bool __cdecl Magpie::Core::DeviceResources::_CreateSwapChain(void)|Multiplane Overlay 支持：是
2023-07-10 10:16:18.262|info|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_InitFrameSource(void)|当前捕获模式：Graphics Capture
2023-07-10 10:16:18.276|info|GraphicsCaptureFrameSource.cpp:bool __cdecl Magpie::Core::GraphicsCaptureFrameSource::Initialize(void)|GraphicsCaptureFrameSource 初始化完成
2023-07-10 10:16:18.276|info|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_InitFrameSource(void)|源窗口尺寸：1279x719
2023-07-10 10:16:18.276|info|Win32Utils.cpp:bool __cdecl Win32Utils::ReadFile(const wchar_t *,class std::vector<unsigned char,class std::allocator<unsigned char> > &)|读取文件：cache\Lanczos_1cfc88f88f10091e3
2023-07-10 10:16:18.276|info|EffectCacheManager.cpp:bool __cdecl Magpie::Core::EffectCacheManager::Load(class std::basic_string_view<wchar_t,struct std::char_traits<wchar_t> >,class std::basic_string_view<wchar_t,struct std::char_traits<wchar_t> >,struct Magpie::Core::EffectDesc &)|已读取缓存 cache\Lanczos_1cfc88f88f10091e3
2023-07-10 10:16:18.276|info|Renderer.cpp:bool __cdecl Magpie::Core::CompileEffect(bool,const struct Magpie::Core::EffectOption &,struct Magpie::Core::EffectDesc &)|编译 Lanczos.hlsl 用时 0.24800001 毫秒
2023-07-10 10:16:18.278|info|Win32Utils.cpp:bool __cdecl Win32Utils::ReadFile(const wchar_t *,class std::vector<unsigned char,class std::allocator<unsigned char> > &)|读取文件：cache\fonts_zh-cn
2023-07-10 10:16:18.278|info|ImGuiImpl.cpp:unsigned long __cdecl Magpie::Core::ThreadProc(void *)|已注册鼠标钩子
2023-07-10 10:16:18.278|info|CursorManager.cpp:bool __cdecl Magpie::Core::CursorManager::Initialize(void)|CursorManager 初始化完成
2023-07-10 10:16:19.067|info|CursorManager.cpp:bool __cdecl Magpie::Core::CursorManager::GetCursorTexture(struct ID3D11Texture2D **,enum Magpie::Core::CursorManager::CursorType &)|已解析光标：0x10003
	类型：Color
2023-07-10 10:16:57.567|error|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_CreateHostWnd(void)|已存在缩放窗口
2023-07-10 10:16:59.775|error|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_CreateHostWnd(void)|已存在缩放窗口
2023-07-10 10:17:00.227|error|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_CreateHostWnd(void)|已存在缩放窗口
2023-07-10 10:18:15.139|info|Renderer.cpp:int __cdecl Magpie::Core::Renderer::_CheckSrcState(void)|源窗口显示状态改变
2023-07-10 10:18:15.139|info|Renderer.cpp:void __cdecl Magpie::Core::Renderer::Render(bool)|源窗口状态改变，退出全屏
2023-07-10 10:18:18.763|info|Renderer.cpp:int __cdecl Magpie::Core::Renderer::_CheckSrcState(void)|源窗口显示状态改变
2023-07-10 10:18:18.763|info|Renderer.cpp:void __cdecl Magpie::Core::Renderer::Render(bool)|源窗口状态改变，退出全屏
2023-07-10 10:18:19.859|info|Renderer.cpp:int __cdecl Magpie::Core::Renderer::_CheckSrcState(void)|源窗口显示状态改变
2023-07-10 10:18:19.859|info|Renderer.cpp:void __cdecl Magpie::Core::Renderer::Render(bool)|源窗口状态改变，退出全屏
2023-07-10 10:18:23.220|info|Renderer.cpp:int __cdecl Magpie::Core::Renderer::_CheckSrcState(void)|源窗口显示状态改变
2023-07-10 10:18:23.220|info|Renderer.cpp:void __cdecl Magpie::Core::Renderer::Render(bool)|源窗口状态改变，退出全屏
2023-07-10 10:18:23.388|info|Renderer.cpp:int __cdecl Magpie::Core::Renderer::_CheckSrcState(void)|源窗口显示状态改变
2023-07-10 10:18:23.388|info|Renderer.cpp:void __cdecl Magpie::Core::Renderer::Render(bool)|源窗口状态改变，退出全屏
2023-07-10 10:18:24.572|info|Renderer.cpp:int __cdecl Magpie::Core::Renderer::_CheckSrcState(void)|源窗口显示状态改变
2023-07-10 10:18:24.572|info|Renderer.cpp:void __cdecl Magpie::Core::Renderer::Render(bool)|源窗口状态改变，退出全屏
2023-07-10 10:23:24.488|info|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_CreateHostWnd(void)|缩放窗口尺寸：1920x1080
2023-07-10 10:23:24.490|info|DeviceResources.cpp:bool __cdecl Magpie::Core::DeviceResources::Initialize(void)|可变刷新率支持：是
2023-07-10 10:23:24.507|info|DeviceResources.cpp:bool __cdecl Magpie::Core::DeviceResources::_TryCreateD3DDevice(struct IDXGIAdapter1 *) noexcept|已创建 D3D Device
	功能级别：11.1
2023-07-10 10:23:24.507|info|DeviceResources.cpp:void __cdecl Magpie::Core::LogAdapter(const struct DXGI_ADAPTER_DESC1 &)|当前图形适配器：
	VendorId：0x1002
	DeviceId：0x1638
	描述：AMD Radeon(TM) Graphics
2023-07-10 10:23:24.509|info|DeviceResources.cpp:bool __cdecl Magpie::Core::DeviceResources::_CreateSwapChain(void)|Hardware Composition 支持：是
2023-07-10 10:23:24.509|info|DeviceResources.cpp:bool __cdecl Magpie::Core::DeviceResources::_CreateSwapChain(void)|Multiplane Overlay 支持：是
2023-07-10 10:23:24.509|info|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_InitFrameSource(void)|当前捕获模式：Graphics Capture
2023-07-10 10:23:24.570|info|GraphicsCaptureFrameSource.cpp:bool __cdecl Magpie::Core::GraphicsCaptureFrameSource::Initialize(void)|GraphicsCaptureFrameSource 初始化完成
2023-07-10 10:23:24.570|info|MagApp.cpp:bool __cdecl Magpie::Core::MagApp::_InitFrameSource(void)|源窗口尺寸：1280x720
2023-07-10 10:23:24.592|info|Win32Utils.cpp:bool __cdecl Win32Utils::ReadFile(const wchar_t *,class std::vector<unsigned char,class std::allocator<unsigned char> > &)|读取文件：cache\Lanczos_1cfc88f88f10091e3
2023-07-10 10:23:24.598|info|EffectCacheManager.cpp:bool __cdecl Magpie::Core::EffectCacheManager::Load(class std::basic_string_view<wchar_t,struct std::char_traits<wchar_t> >,class std::basic_string_view<wchar_t,struct std::char_traits<wchar_t> >,struct Magpie::Core::EffectDesc &)|已读取缓存 cache\Lanczos_1cfc88f88f10091e3
2023-07-10 10:23:24.598|info|Renderer.cpp:bool __cdecl Magpie::Core::CompileEffect(bool,const struct Magpie::Core::EffectOption &,struct Magpie::Core::EffectDesc &)|编译 Lanczos.hlsl 用时 28.097002 毫秒
2023-07-10 10:23:24.600|info|Win32Utils.cpp:bool __cdecl Win32Utils::ReadFile(const wchar_t *,class std::vector<unsigned char,class std::allocator<unsigned char> > &)|读取文件：cache\fonts_zh-cn
2023-07-10 10:23:24.600|info|ImGuiImpl.cpp:unsigned long __cdecl Magpie::Core::ThreadProc(void *)|已注册鼠标钩子
2023-07-10 10:23:24.611|info|CursorManager.cpp:bool __cdecl Magpie::Core::CursorManager::Initialize(void)|CursorManager 初始化完成
2023-07-10 10:23:25.018|info|CursorManager.cpp:bool __cdecl Magpie::Core::CursorManager::GetCursorTexture(struct ID3D11Texture2D **,enum Magpie::Core::CursorManager::CursorType &)|已解析光标：0x10003
	类型：Color
2023-07-10 10:23:33.151|info|CursorManager.cpp:bool __cdecl Magpie::Core::CursorManager::GetCursorTexture(struct ID3D11Texture2D **,enum Magpie::Core::CursorManager::CursorType &)|已解析光标：0x10019
	类型：Color
2023-07-10 10:23:48.834|info|ImGuiImpl.cpp:unsigned long __cdecl Magpie::Core::ThreadProc(void *)|已销毁鼠标钩子

**Comment by Blinue** [comment] 2023-07-10 02:46
Duplicate of #141

**Closed by Blinue** 2023-07-10 02:46 UTC
Labels: bug
