### ISSUE TITLE
How to cap Magpie FPS when using Desktop Duplication?

### ISSUE THREAD

**Issue by advanced03** [Blinue/Magpie#680] opened 2023-07-14 12:33 UTC
### Question 问题

Basically the title. I'm reading a visual novel and I want to cap the FPS to 60 instead of it running at my monitors refresh rate constantly.

**Comment by Blinue** [comment] 2023-07-15 14:27
Duplicate of #378

This feature is already under development -> #643

**Closed by Blinue** 2023-07-15 14:27 UTC
Labels: question

**Comment by advanced03** [comment] 2023-07-15 14:35
> Duplicate of #378
> 
> This feature is already under development -> #643

Sorry didn't know, I don't speak Chinese or Japanese my bad
