### ISSUE TITLE
Magpie stutters due to fps drop

### ISSUE THREAD

**Issue by PenguinDOOM** [Blinue/Magpie#78] opened 2021-08-24 04:43 UTC
I tested it with genshin impact and it works fine except for the cursor issue. 
However, in some places there is stuttering due to Magpie's fluctuating fps. ( In game fps is kept at 60fps ) 
Holding down alt while moving keeps the fps high enough to describe the cursor, so no stuttering.

**Comment by zaifan** [comment] 2021-08-25 08:11
I also played genshin impact, but had no such problems, and no stuttering. because magpie will follow the fps in the game, if the game runs at 30 fps then magpie is also 30 fps (except when playing with the mouse, then when the mouse is moved, the magpie fps will rise to 60 fps)

**Comment by PenguinDOOM** [comment] 2021-08-25 10:22
I tested it again and the fps didn't drop anymore, so it may be a bug and not a performance issue. However, when I move the mouse, the fps increases and it doesn't look as smooth as when I use alt+enter full screen.

**Comment by PenguinDOOM** [comment] 2021-08-25 10:23
I restarted the game and magpie, and magpie's fps dropped again.

**Comment by CoderStone** [comment] 2021-08-28 02:05
1650 should be much better than your integrated graphics..

**Comment by zaifan** [comment] 2021-08-31 17:37
@PenguinDOOM hi . I've tested magpie fsr on genshin again with unlock fps (60 fps) and I also get stuttering, not only magpie's fps fluctuated (50-60 fps) but genshin fps also drop from 60 to 56 when moving

**Comment by PenguinDOOM** [comment] 2021-09-01 01:24
@zaifan Yes, I have the same problem. Although not as bad as lossless scaling, but it also affects the fps of the genshin impact.

**Comment by PenguinDOOM** [comment] 2021-09-01 01:28
I was wondering what magpie uses, FP16 or FP32.

**Comment by zaifan** [comment] 2021-09-01 07:32
Magpie FSR seems to need a while to adapt until the fps can reach 60 again when entering a new place. but I don't think this is a problem with magpie only but also with genshin because only genshin has this problem, I have tested many games such as battlefield V (60 fps), ac valhalla, wd legion, pes 21 (60 fps) and have not experienced this kind of problem.

**Comment by zaifan** [comment] 2021-09-02 15:46
@PenguinDOOM  I think I've found the cause of the stuttering in genshin, the cause is because the ZFGameBooster.exe application runs using the gpu. when I end the task through task manager, the stuttering in genshin is gone

**Comment by PenguinDOOM** [comment] 2021-09-02 16:40
@zaifan If taskkill ZFGameBrowser.exe, it will prevent opening in game notices. In addition, it gets stuck at the end of the game.
I've tried other scaling modes and the only problem with fps increasing when moving the mouse is fsr.
I don't know why magpie's fps is low for a while after startup. It's probably a bug, not a performance problem, since the fps increases when moving the mouse and becomes almost the same as the in game fps after a while.

**Comment by PenguinDOOM** [comment] 2021-09-02 16:42
Restarting the gpu driver with Ctrl + Shift + B causes the fps to drop as it did right after startup.

**Comment by PenguinDOOM** [comment] 2021-09-02 16:46
The problem of fps dropping for a while after startup has happened with other games as well.

**Comment by PenguinDOOM** [comment] 2021-09-02 16:49
As for ZFGameBrowser.exe, I am using nvidia gpu to process it.

**Comment by PenguinDOOM** [comment] 2021-09-16 06:28
I tried the d3d branch and the only frame drop was in GraphicsCapture (WinRT Capture).

**Comment by Blinue** [comment] 2021-09-16 06:49
Thanks for the feedback. It seems that the performance of GraphicsCapture varies on different computers.

**Comment by Blinue** [comment] 2022-05-10 07:55
I am closing this as it is outdated. If you encounter this problem in the latest version, please file a new issue.

**Closed by Blinue** 2022-05-10 07:55 UTC
Labels: performance
