### ISSUE TITLE
v0.8.0 flagged as Trojan

### ISSUE THREAD

**Issue by dsdsdsdgg** [Blinue/Magpie#281] opened 2022-01-20 15:08 UTC
### Magpie version 程序版本

v0.8.0

### Windows version 系统版本

Windows 10 Pro 20H2

### Related screenshot (optional) 相关截图（可选）

![image](https://user-images.githubusercontent.com/35578434/150364281-0196505b-9b23-4ce6-bf2a-453b46e6f5f0.png)
![image](https://user-images.githubusercontent.com/35578434/150364450-ae8b715d-211a-453f-bb06-862d46a9d95a.png)

### Reproduction steps 复现步骤

1. Download release v0.8.0
2. Scan "Magpie_v0.8.0.zip" and "Magpie.exe" using virustotal.com

https://www.virustotal.com/gui/file/90d338dcd6507ce1f3e87beea61e3853ca8c59ce726587b6835fb90fc05bb956
https://www.virustotal.com/gui/file/b575485c0ee300d3a219f35c5dc5f7ec519f9a2ea9550e1958d733c1f1a09daf

### Log files 日志文件

[issue not in log]

**Comment by Blinue** [comment] 2022-01-20 15:14
Duplicate of #276

**Closed** 2022-01-20 15:14 UTC
Labels: bug
