### ISSUE TITLE
option to resize window+apply effects+scaling (no full screen)

### ISSUE THREAD

**Issue by TheKillZoneDead** [Blinue/Magpie#699] opened 2023-08-10 01:52 UTC
### Expected behavior 预期的功能

I have very old RPG Maker games and I'm not really used to playing RPGs in full screen mode as I'm usually doing other things on PC at the same time as playing.

Games in RPG Maker VX/ACE, for example, run in a roughly 642x507 window with no resizing capability. I can force the window to the size I want using other programs, however, image quality is lost.

I've tried window resizing + scaling using Magpie and only managed to run the game at the size I want, but full screen with black borders.

**My main request** is to add an effect that allows the window to be resized while scaling the internal resolution of the window.

### Alternative behavior (optional) 近似的功能（可选）

**Alternative behavior** would be to add a function that allows you to resize the window and modify the sharpness without going to full screen mode (do not apply any type of scaling to the window, just add effects to the image).

I know that with the nvidia panel or Reshade maybe these things can be done, but if what I asked for in expectations can be done, that would allow playing with other effects with Magpie since it is a much more comfortable software to use.

Thanks for reading me. =)

**Comment by Blinue** [comment] 2023-08-10 10:47
Duplicate of #135. Magpie does not modify the original window, but only creates a new one with the zoomed-in view. We are still discussing the best way to implement this feature.

**Closed by Blinue** 2023-08-10 10:47 UTC
Labels: enhancement
