### ISSUE TITLE
HELP! Magpie disabled & uninstalled, but the software continues fuctioning!

### ISSUE THREAD

**Issue by TheCrusader39** [Blinue/Magpie#494] opened 2023-03-05 14:01 UTC
### Magpie version 程序版本

v0.9.1

### Windows version 系统版本

Windows 10 Pro 22h2 OS build 19045.2604

### Related screenshot (optional) 相关截图（可选）

After using this software I am unable to revoke its access. Despite disabling it with Alt+F11 toggle and seeing my gpu load rise since I stopped operation, the software will resume operating after I restart the game with zero input from me and regardless if the software is open and running or not.

I've scanned my background processes for any hints of Magpie and there are none, yet somehow the software is still going. I tried restarting the computer but that didn't work and now I'm going crazy.

I tried two titles with this software. Valheim and Monster Hunter Rise. In my testing the software worked as advertised. The games ran faster and I saw an uptick in performance in both titles. I was very pleased. But I noticed when I restarted the games without the software running and after toggling Alt+F11 to disable it Magpie was still operating.

I tried deleting my game installations and having steam rebuild them from scratch, but magpie was still continuing its functionality. Furthermore, Monster Hunter Rise's native DLSS implementation is now broken for me and repairing the game didn't work. Enabling DLSS quality mode now triggers a performance loss. Its now adding additional load to my gpu rather than lowering it with my frame rate being capped at the same refresh rate before and after. 

At first I thought Riva-tuner was misinterpreting my statistics on screen, but GPU-Z and HWMonitor both are reporting the same numbers, and I can confirm Magpie is still operating.

This whole experience has been very bizarre, and very upsetting. Is there some folder I missed that's sending instructions to Magpie to continue its operations?! Or some leftover residue of some kind I looked over that's somehow making this possible?

On the upside no other games are acting up from what I have seen since I didn't run Magpie with them. I booted up Returnal and it ran as expected. Dlss functioned correctly in that game and I think its safe to say my other titles are safe too, but Valeheim and MHR remain broken and nothing I have tried has restored them to normal behavior.

### Reproduction steps 复现步骤

Unzipped the archive and dragged the folder to my desktop.

Ran the software and left everything at default.

Booted up Monster Hunter Rise/Valheim and witnessed a performance increase according to Rivatuner after pressing Alt-F11 to activate magpie's scaler.

Toggled it off and performance returned back to the norm. Everything is fine.

Restarted the game with Magpie closed and after disabling it beforehand but I'm still getting the same performance as if it was on and running when its not. 

### Log files 日志文件

[Magpie.log](https://github.com/Blinue/Magpie/files/10891953/Magpie.log)
[Runtime.log](https://github.com/Blinue/Magpie/files/10891954/Runtime.log)

**Comment by Blinue** [comment] 2023-03-05 14:29
Hello. 

According to the logs, Magpie has indeed exited. How did you determine that it was still running? In order to use Magpie, you must run the game in windowed mode, so it is obvious whether Magpie is working or not. Based on your description, I can confirm that this is a behavior of the game itself.

**Comment by TheCrusader39** [comment] 2023-03-05 14:59
> Hello.
> 
> According to the logs, Magpie has indeed exited. How did you determine that it was still running? In order to use Magpie, you must run the game in windowed mode, so it is obvious whether Magpie is working or not. Based on your description, I can confirm that this is a behavior of the game itself.
> 
> I guess these games use F11 as the shortcut for fullscreen mode, which conflicts with Magpie's shortcut keys. Magpie has indeed exited.

How can I determine that Magpie is still operating? That is very simple to do. I look at graphically demanding scene without variables. So take MHR character select screen. Targeting a locked refresh rate of 240 my gpu load is at 69 load with Magpie activated during this scene. when I deactivate it it skyrockets to 89 load. OK, that's normal. Its working as intended. Now I deactivate it again, close the game, shut down Magpie, relaunch the game and I'm somehow still getting the same performance as if magpie was still on despite shutting it down and deactivating it beforehand. I can't wrap my mind around it.

**Comment by Blinue** [comment] 2023-03-05 15:08
Here is a method to check if Magpie is running: press Ctrl+Alt+D while in fullscreen mode, which will activate Magpie's in-game overlay (looks like [this](https://user-images.githubusercontent.com/34770031/167125685-5ed80262-6722-41da-87c1-a43b594f8396.png)). If you can see the overlay, it means that Magpie is running.

**Comment by TheCrusader39** [comment] 2023-03-05 15:34
> Here is a method to check if Magpie is running: press Ctrl+Alt+D while in fullscreen mode, which will activate Magpie's in-game overlay (looks like [this](https://user-images.githubusercontent.com/34770031/167125685-5ed80262-6722-41da-87c1-a43b594f8396.png)). If you can see the overlay, it means that Magpie is running.

I couldn't get the overlay to display. Not while Magpie was running or with it deactivated. I tried changing the key bidding but I had no such success. I meet all the requirements listed to operate Magpie but the overlay is not functioning on my end. All I know is I'm getting the same performance as if Magpie was on when in fact its not. Futhermore enabling dlss is also producing some weirdness as well such as increasing load when it should have the opposite effect since my frame-rate is locked. 

Moments earlier I performed a total removal of my gpu's drivers with DDU and upgraded to the latest drivers 531.18 and I'm still experiencing these behaviors. Prior to using Magpie I had a functioning DLSS in Monster Hunter Rise and now its all gone haywire.

**Comment by Blinue** [comment] 2023-03-05 15:42
So Magpie is not running at all. Scale a regular window, such as File Explorer, and you should see the in-game overlay.

**Comment by TheCrusader39** [comment] 2023-03-05 16:07
When I pressed Alt+F11 on my desktop it became distorted. Pressing it again restored it back to normal. However the overlay didn't function. So Magpie is operating and doing something, but the overlay is a bust. So I had a thought. Maybe clearing Magpie stored data from my AppData Local Directory would solve this problem and voilà, that did the trick.

Now with the overlay functioning on the desktop and now in-game and can report my gpu load is still the same as before. I am seeing the same overhead on my gpu prior to fixing the overlay and after. So it was functioning beforehand and its definitely functioning now and my load is the same as i described. 

How can deactivating Magpie impose a loss in performance if nothing happened in the first place as you are alluding to? If its getting deactivated, and my gpu load increases, then an up scaling filter that was being applied was removed.

**Comment by Blinue** [comment] 2023-03-06 00:52
> Unzipped the archive and dragged the folder to my desktop.
> 
> Ran the software and left everything at default.
> 
> Booted up Monster Hunter Rise/Valheim and witnessed a performance increase according to Rivatuner after pressing Alt-F11 > to activate magpie's scaler.
> 
> Toggled it off and performance returned back to the norm. Everything is fine.
> 
> Restarted the game with Magpie closed and after disabling it beforehand but I'm still getting the same performance as if it was > on and running when its not.

It seems that you have not been using Magpie correctly. Although there is no official support, some people have found that Magpie can be used to improve game performance, and here are the detailed steps:

1. First, run the game in its native fullscreen mode and record the framerate, let's say it's 50 FPS.
2. Switch to windowed mode, which can provide some performance boost due to the smaller rendering size. Let's assume the framerate is now 60 FPS.
3. Press Magpie's shortcut key while the game is in windowed mode, and Magpie will stretch the game back to fullscreen. At this point, Magpie will use some resources, so the framerate of the game may slightly drop, let's say it's now 55 FPS.
4. It can be considered that Magpie has increased the framerate by 5 FPS compared to the game's native fullscreen mode.

Magpie does not do anything except scaling, it cannot improve game performance, and the performance improvement is actually caused by running the game in windowed mode.

**Comment by Blinue** [comment] 2023-03-25 11:09
Closing this issue as it is no longer active.

**Closed by Blinue** 2023-03-25 11:09 UTC
Labels: question
