### ISSUE TITLE
Add frame interpolation to increase fps, like avisynth interframe or smooth video project (SVP).

### ISSUE THREAD

**Issue by motoleon** [Blinue/Magpie#656] opened 2023-06-11 21:27 UTC
### Expected behavior 预期的功能

Add frame interpolation to increase fps, like avisynth interframe or smooth video project (SVP). Using CPU or GPU to do that. ITs like DLSS but using simple algorithms. Thanks.

**Comment by Blinue** [comment] 2023-06-12 01:16
Duplicate of #634
See also: #498

**Closed by Blinue** 2023-06-12 01:16 UTC
Labels: enhancement
