### ISSUE TITLE
Resize to full screen but in windowed mode

### ISSUE THREAD

**Issue by Fuwiz** [Blinue/Magpie#1000] opened 2024-09-26 11:30 UTC
### Question 问题

Can i resize window of game from like 640x480 in windowed mode to 1920x1080 not to full screen, but to windowed mode? 
I mean to fill whole screen like browser (firefox/chrome)

**Comment by Blinue** [comment] 2024-09-29 07:16
Duplicate of #135

**Closed by Blinue** 2024-09-29 07:16 UTC
Labels: question
