### ISSUE TITLE
App Profiles & Automatic Enabling

### ISSUE THREAD

**Issue by DimetryBadcoder** [Blinue/Magpie#396] opened 2022-06-26 17:05 UTC
### Expected behavior 预期的功能

Ability to create and edit profiles for the different applications that I can choose. 
Option to automated applying the chosen filter to the application according to its profile. 

P. S.: Many thanks for your work and greetings from Russia!

**Comment by Blinue** [comment] 2022-06-27 00:29
Thank you. This feature is under development.

Duplicate of #385 and #193

**Closed by Blinue** 2022-06-27 00:29 UTC
Labels: enhancement
