### ISSUE TITLE
Window doesn't want to upscale with version 0.11.1 but did with 0.10.6

### ISSUE THREAD

**Issue by Freestalkerdotfr** [Blinue/Magpie#983] opened 2024-08-25 16:06 UTC
### Magpie version 程序版本

0.11.1

### Windows version 系统版本

Win10 22H2 / Build 19045

### Reproduction steps 复现步骤

Hello,
It seems that there is an error with the renderer.cpp. Is it possible to be fixed ? I tried 0.10.6 and it worked.

### Log files 日志文件

[magpie.log](https://github.com/user-attachments/files/16741061/magpie.log)

**Comment by Blinue** [comment] 2024-08-26 06:58
Duplicate of #979

**Closed by Blinue** 2024-08-26 06:58 UTC
Labels: bug
