### ISSUE TITLE
Automatically Choose Algorithm Based on Program

### ISSUE THREAD

**Issue by kanjieater** [Blinue/Magpie#449] opened 2022-11-10 22:55 UTC
### Expected behavior 预期的功能

Other applications like [DS4Windows ](https://ds4-windows.com/)or [BorderlessGaming](https://github.com/Codeusa/Borderless-Gaming) allow you to set configuration on a per program basis.

I have some apps that I like to use different settings with, so it would be convenient to have the program automatically use the right algorithm with the right game.

**Comment by Blinue** [comment] 2022-11-11 00:50
Duplicate of #385 
Previewing in https://github.com/Blinue/Magpie/releases/tag/v0.10.0-preview1

**Closed by Blinue** 2022-11-11 00:50 UTC
Labels: enhancement
