### ISSUE TITLE
Add Frame Gen option to FSR

### ISSUE THREAD

**Issue by nehdisu** [Blinue/Magpie#802] opened 2024-01-05 09:29 UTC
### Expected behavior 预期的功能

As FSR 3 is now open sourse, i wish that the frame gen thing could work in any game. So that how i think it should work:

(Add it as an option in menu)
when activated, it will work just like Afmf from the driver version. 
Doing it this way it should work in any game (And yes, i know it will have ghosting in ui) 

Sound easy, but is it do able?

**Comment by 2ji3150** [comment] 2024-01-06 02:07
Duplicate of #634

**Comment by nehdisu** [comment] 2024-01-06 02:59
They did add it in Lossless Scaling, but it isn't free.
It's the logic of demand and supply.
Everyone wants this, even if it ended up having a terrible implementation, it would be good to at least have the option available to the curious.

**Comment by Blinue** [comment] 2024-01-06 06:53
FSR 2/3 are designed to integrate with game engines, and a universal injector is impossible to achieve. To my knowledge, Lossless Scaling also does not support FSR 2/3. Let me clarify: Magpie has no plans to implement FSR 2/3 or frame interpolation features, as they are not its design goals. Thank you for your suggestion.

**Closed by Blinue** 2024-01-06 06:53 UTC
Labels: enhancement
