### ISSUE TITLE
An option to launch directly into taskbar without showing the UI

### ISSUE THREAD

**Issue by nixxou** [Blinue/Magpie#908] opened 2024-05-11 22:54 UTC
### Expected behavior 预期的功能

I have an usecase where i need to launch Magpie after the game load.

My issue is that for some game, if i launch it after the game, it show it's main form and steal the game focus. I would like if there is a way to launch it directly into the tray icon without showing any window.

### Alternative behavior (optional) 近似的功能（可选）

There is already in the config something like that : 
  "windowPos": {
    "centerX": 3602.5,
    "centerY": 892.0,
    "width": 773.0,
    "height": 544.0,
    "maximized": false
  },

It would make sense to hide an attribute hidden or if that's problematic at least something like minimized

**Comment by Blinue** [comment] 2024-05-12 14:36
Duplicate of #698

**Closed by Blinue** 2024-05-12 14:36 UTC
Labels: enhancement
