### ISSUE TITLE
[Feature Request] Auto upscaling when app/game opens

### ISSUE THREAD

**Issue by nitanmarcel** [Blinue/Magpie#433] opened 2022-10-02 16:31 UTC
### Expected behavior 预期的功能

Would be nice if I could configure a game that each time I open it, magpie will automatically resize the window.

This feature is also available in Looseless Scalling.

**Comment by Blinue** [comment] 2022-10-03 12:36
Duplicate of #193

**Closed by Blinue** 2022-10-03 12:36 UTC
Labels: enhancement
