### ISSUE TITLE
Capture Method: Desktop Duplication is not working

### ISSUE THREAD

**Issue by amy10111111111** [Blinue/Magpie#622] opened 2023-05-19 16:06 UTC
### Magpie version 程序版本

0.10.2

### Windows version 系统版本

win10 Home

### Related screenshot (optional) 相关截图（可选）

![Untitled](https://github.com/Blinue/Magpie/assets/102473286/e1d1c7e3-1096-483d-b8ec-14475efdf26d)

### Reproduction steps 复现步骤

So Iam trying to use the desktop duplication so that I can capture the game and translation box at the same time but it is not working what is the cause of this?

### Log files 日志文件

2023-05-19 19:03:06.194|info|XamlApp.cpp:Initialize|程序启动
	版本：v0.10.2
	管理员：否
2023-05-19 19:03:06.196|info|XamlApp.cpp:Initialize|已经有一个实例正在运行
2023-05-19 19:03:35.226|info|ShortcutService.cpp:operator ()|热键 Scale 激活（Keyboard Hook）
2023-05-19 19:03:35.232|info|MagApp.cpp:_CreateHostWnd|缩放窗口尺寸：1920x1080
2023-05-19 19:03:35.233|info|DeviceResources.cpp:Initialize|可变刷新率支持：是
2023-05-19 19:03:35.293|info|DeviceResources.cpp:_TryCreateD3DDevice|已创建 D3D Device
	功能级别：11.1
2023-05-19 19:03:35.293|info|DeviceResources.cpp:LogAdapter|当前图形适配器：
	VendorId：0x10de
	DeviceId：0x1c8c
	描述：NVIDIA GeForce GTX 1050 Ti
2023-05-19 19:03:35.416|info|DeviceResources.cpp:_CreateSwapChain|Hardware Composition 支持：否
2023-05-19 19:03:35.416|info|DeviceResources.cpp:_CreateSwapChain|Multiplane Overlay 支持：否
2023-05-19 19:03:35.416|info|MagApp.cpp:_InitFrameSource|当前捕获模式：Desktop Duplication
2023-05-19 19:03:35.461|error|DesktopDuplicationFrameSource.cpp:Initialize|DuplicateOutput 失败
	HRESULT：0x887A0004
2023-05-19 19:03:35.461|critical|MagApp.cpp:_InitFrameSource|初始化 FrameSource 失败
2023-05-19 19:03:35.461|error|MagApp.cpp:Start|_InitFrameSource 失败

**Comment by Blinue** [comment] 2023-05-20 05:40
Duplicate of #497

**Comment by amy10111111111** [comment] 2023-05-20 09:58
> Duplicate of #497

So I fixed the problem however for some reason the screen become Laggy and the motion is slow is this normal?

**Comment by Blinue** [comment] 2023-05-20 12:15
For hybrid architectures, the graphics card connected to the monitor is usually much slower because it is integrated in the CPU.  I suggest you do not use Desktop Duplication.

**Comment by amy10111111111** [comment] 2023-05-21 13:54
I see I guess I will switch to another capture method thanks

**Closed** 2023-05-22 03:40 UTC
Labels: question
