### ISSUE TITLE
[Feature Request] Favorite Process List

### ISSUE THREAD

**Issue by LOuroboros** [Blinue/Magpie#385] opened 2022-06-07 00:35 UTC
It would be cool if Magpie had in its configuration a list of processes that could be edited by the user that would be read whenever an application is first opened,
If this application's process name is present on the list, Magpie would then scale it automatically without having the user do so manually through Alt + F11.
It would complement the "Restore Fullscreen when Source Window Regains Focus" option nicely, in my opinion.

So, to put an example, the user could open Magpie's Options, go to the "Fav. Process" tab or whatever, and then there would be a list with the processes currently added, and then there would be a text field to add new process names.
If I had "Game.exe" added to that list for example, Magpie would then automatically scale it once I opened the executable file that creates a process with that same name :eyes:

**Comment by Blinue** [comment] 2022-06-07 00:57
Thank you. This is a duplicate of #193.

I'm about to implement this (or something similar) in v0.10. I am not sure how to identify a window/process, since an executable file may generate multiple processes and a process may have multiple windows.

**Comment by nitanmarcel** [comment] 2022-10-03 14:30
> Thank you. This is a duplicate of #193.
> 
> I'm about to implement this (or something similar) in v0.10. I am not sure how to identify a window/process, since an executable file may generate multiple processes and a process may have multiple windows.

Should pe possible to get the root window. One of the possible ways to do this is https://stackoverflow.com/a/6202623

**Comment by Blinue** [comment] 2023-03-25 11:12
Implemented in v0.10 🎉

**Closed by Blinue** 2023-03-25 11:12 UTC
Labels: enhancement
