### ISSUE TITLE
Program always crashes when using WinRT, only works with GDI

### ISSUE THREAD

**Issue by zemanyak** [Blinue/Magpie#29] opened 2021-08-04 08:57 UTC
Hi,

I'm using Windows 10 1903 and a 1080p screen. The program works fine with GDI but every time I use WinRT, the program just closes after a few seconds, no matter the upscaling algorithm I use.

Is there any way I can check where the problem comes from ?

Thank you for your work.

**Comment by cosminm13** [comment] 2021-08-04 10:53
I'm encountering the same problem on Windows 1909, WinRT doesn't work, it always crashes.

Also, in some games, when using GDI, all I can see is a black screen, though I can see the fps counter and hear the game's sound.

**Comment by Blinue** [comment] 2021-08-04 12:48
Winrt capture mode is faster and can capture more types of windows, but it is not very reliable.

I can't determine the cause of the crash at the moment, as there is no information available for debugging. I will add logging in v0.6, so it should be much easier to find the problem then.

**Comment by kimberly990** [comment] 2021-08-05 03:36
`Faulting module name: ucrtbase.dll, version: 10.0.19041.789, time stamp: 0x2bd748bf`

That's the error I see in Event Viewer on Windows. This happens every time I press Alt+F11. I know there's no logging right now, but that might help. This is a nice program and I look forward to 0.6

**Comment by Blinue** [comment] 2021-08-05 04:09
Thank you, it helps. I will update if any progress.

**Comment by Blinue** [comment] 2021-08-05 11:40
Hello, this build should work. I've tested it in a VM.

[Release.zip](https://github.com/Blinue/Magpie/files/6938278/Release.zip)

**Comment by zemanyak** [comment] 2021-08-05 13:08
I can confirm this is now working. Many thanks !

**Comment by Blinue** [comment] 2021-08-05 13:16
This fix will be released in v0.6

**Comment by kimberly990** [comment] 2021-08-05 14:17
Hey, that's great! Thank you

**Closed** 2021-08-05 15:38 UTC
Labels: bug
