### ISSUE TITLE
Add command line options

### ISSUE THREAD

**Issue by Nodoyuna02** [Blinue/Magpie#1002] opened 2024-09-27 21:54 UTC
### Expected behavior 预期的功能

To use in batch files to run games to fullscreen without needing to open the program and pressing the keys to make the game fullscreen
Kind of making the process more direct and in an automatic way
I don't know if it's possible, but I think it would be a great addition to magpie
Thanks in advance

**Comment by Blinue** [comment] 2024-09-29 07:18
Duplicate of #686

**Closed by Blinue** 2024-09-29 07:18 UTC
Labels: enhancement
