### ISSUE TITLE
Be able to use windows at top like translator or ocr

### ISSUE THREAD

**Issue by rasbayri** [Blinue/Magpie#700] opened 2023-08-13 16:10 UTC
### Expected behavior 预期的功能

Be able to see the upscaled game and tranlsator at the same time like in https://github.com/Codeusa/Borderless-Gaming

The example of how it looks like
![2022-05-29_01-21](https://github.com/Blinue/Magpie/assets/88791721/b772553c-ef34-4dc9-89b9-597119924e59)

**Comment by Blinue** [comment] 2023-08-14 08:03
Duplicate of #441

Try the Desktop Duplication capture method. You can also report compatibility issues with Magpie to the translator/ocr.

**Closed by Blinue** 2023-08-14 08:03 UTC
Labels: enhancement
