### ISSUE TITLE
Add an option to force the target window scaling to a specific size

### ISSUE THREAD

**Issue by ryrun** [Blinue/Magpie#723] opened 2023-09-29 20:19 UTC
### Expected behavior 预期的功能

It would be nice, if we can specify a specific window resolution, before scaling is applied.
So i can set up a typical 720p width and height, press the scaling shortcut, magpie scales the target window to this size an scales up.

**Comment by Blinue** [comment] 2023-11-24 05:15
Sorry for not noticing this issue, this feature is already in the plan.

Duplicate of #173

**Closed by Blinue** 2023-11-24 05:15 UTC
Labels: enhancement
